version: "3.7"

services:

  mongodb:
    image: mongo:4.2.7
    restart: unless-stopped
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7.30
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password

  keycloak:
    image: jboss/keycloak:10.0.2
    restart: unless-stopped
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - JDBC_PARAMS=useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  # App backend service
  beer-api:
    # Configuration for building the docker image for the backend service
    build:
      context: beers-api # Use an image built from the specified dockerfile
      dockerfile: Dockerfile
    environment:
      - MONGODB_HOST=mongodb
      - KEYCLOAK_HOST=keycloak
    ports:
      - "9080:8080"
    restart: unless-stopped
    depends_on: 
      - mongodb 
      - keycloak

  # Frontend Service 
  beer-ui:
    build:
      context: beers-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - beer-api
      - keycloak

